---
title: "Hello, and welcome to my website!"
---
I’m Gabe Rice, a Computer Science major and a Philosophy minor at Sewanee University.

I'm a technology enthusiast with a passion for solving coding problems for my classes, building and upgrading my computer, flying drones, and gaming online with friends. At Sewanee, I've honed my communication skills, particularly in written and oral forms, which are integral parts of our curriculum.

In addition to being a full-time student, I balance multiple campus jobs. At Stirlings, our campus coffee shop, I've developed strong customer service skills through daily interactions with customers. As the drone pilot for the Sewanee varsity football program, I capture game and practice footage, combining my technical skills with my love for drones. As a computer science tutor, I support students in introductory and intermediate courses like Python programming, data structures, and algorithms. My role involves helping students debug code, grasp key concepts, and enhance their problem-solving abilities.

Thanks for visiting my page, please select some of the other sections to learn more about my experiences!  
